
" Vim syntax file for SmartBasic
" Laird Technologies 2013

if exists("b:current_syntax")
  finish
endif

let b:current_syntax = "smartbasic"

syn case ignore

" Preprocessor Keywords
syn keyword smartbasicPreProc #define #include #set

" Keywords 1
syn keyword smartbasicKeyword1 #define #include integer.h' integer.o' integer.b' 
			\ AS BP DO IF TO DIM FOR SUB CALL CASE ELSE LONG NEXT REDO STEP STOP 
			\ THEN BREAK BYREF BYVAL ENDIF FLOAT PRINT ULONG UNTIL WHILE DOWNTO 
			\ ELSEIF ENDSUB SELECT SPRINT STRING DISABLE DOWHILE ENDFUNC EXITSUB 
			\ INTEGER ONERROR ONEVENT CONTINUE ENDWHILE EXITFUNC FUNCTION ENDSELECT 
			\ WAITEVENT THROWEVENT ONFATALERROR

" smartBASIC Functions
syn keyword smartbasicFunction STRLEN GETLASTERROR LEFT$ RIGHT$ MID$ STRPOS MIN MAX 
			\ ABS STRCMP STRVALDEC STRESCAPE$ STRESCAPEEX$ STRGETCHR STRSETCHR 
			\ STRSETBLOCK TABLEINIT TABLEADD TABLELOOKUP NVRECORDGET NVRECORDGETEX
			\ NVRECORDSET STRFILL SYSINFO EXITCODE STRHEX2BIN STRSUM STRXOR STRHEXIZE$
			\ STRDEHEXIZE$ STRSPLITLEFT$ CIRCBUFCREATE CIRCBUFWRITE CIRCBUFOVERWRITE
			\ CIRCBUFREAD CIRCBUFITEMS SYSINFO$ EXTRACTSTRTOKEN EXTRACTINTTOKEN
			\ NVCFGKEYGET NVCFGKEYSET TIMERRUNNING TIMERIOCTL UARTOPEN UARTINFO
			\ UARTWRITE UARTREAD UARTREADN UARTREADMATCH UARTGETCTS UARTCLOSEEX FOPEN
			\ FSEEK FTELL FILELEN FREAD FREADUNTIL EXTRACTFLOATTOKEN EXP LOG LOG10 SQRT
			\ SIN COS TAN ASIN ACOS ATAN CEIL FLOOR FABS FMOD ISNAN ISINF ISFINITE SINH
			\ COSH TANH ASINH ACOSH ATANH POW ROUND PI SETPWRSUPPLYTHRESHMV
			\ SYSTEMSTATESET READPWRSUPPLYMV ERASEFILESYSTEM SENDMSGAPP VERBOSEERR$
			\ RAND RANDEX GETTICKCOUNT GETTICKSINCE UARTIOCTL BLESETADDRESSTYPE
			\ BLESETADDRESSTYPEEX BLEGETADVERTISINGADDRESS$ BLEGETDEVICENAME$
			\ BLEGAPSVCINIT BLEADVRPTINIT BLESCANRPTINIT BLESETCURCONNPARMS
			\ BLEGETCURCONNPARMS BLEGETCURCONNSECINFO BLEOVERWRITEBOND BLEATTRMETADATA
			\ BLEATTRMETADATAEX BLECHARNEW BLECHARDESCUSERDESC BLECHARDESCPRSTNFRMT
			\ BLECHARDESCADD BLECHARCOMMIT BLESERVICENEW BLESERVICECOMMIT
			\ BLESVCADDINCLUDESVC BLEAUTHORIZECHAR BLEAUTHORIZEDESC BLECHARVALUEWRITE
			\ BLECHARVALUENOTIFY BLECHARVALUEINDICATE BLECHARVALUEREAD BLECHARDESCREAD
			\ BLEENCODE8 BLEDECODES8 BLEDECODEU8 BLEENCODE16 BLEDECODES16 BLEDECODEU16
			\ BLEENCODE24 BLEDECODES24 BLEDECODEU24 BLEENCODE32 BLEDECODE32
			\ BLEENCODEFLOAT BLEDECODEFLOAT BLEENCODESFLOAT BLEENCODESFLOATEX
			\ BLEDECODESFLOAT BLEENCODETIMESTAMP BLEDECODETIMESTAMP BLEENCODEBITS
			\ BLEDECODEBITS BLEENCODESTRING BLEDECODESTRING BLEHANDLEUUID16
			\ BLEHANDLEUUID128 BLEUUIDFROMHANDLE BLEHANDLEUUIDSIBLING
			\ BLEADVRPTADDUUID128 BLEGETADBYINDEX BLEGETADBYTAG BLESERVICECHANGEDNTFY
			\ BLEGETCONNHANDLEFROMADDR BLEGETADDRFROMCONNHANDLE
			\ BLEGETCONNHANDLEFROMRESOLVEDADDR BLEGETRESOLVEDADDRFROMCONNHANDLE
			\ BLEADVRPTADDUUID16 BLEADVRPTSCOMMIT BLESVCREGDEVINFO BLECONNMNGRUPDCFG
			\ BLESECMNGRJUSTWORKSCONF BLESECMNGRKEYSIZES BLESECMNGRIOCAP
			\ BLESECMNGRBONDREQ BLESECMNGRPAIRCONF BLESECMNGRAUTHFAILPREF
			\ BLESECMNGRLESCPAIRINGPREF BLESECMNGRLESCKEYPRESSENABLE
			\ BLESECMNGRLESCKEYPRESSNOTIFY BLEADVRPTAPPENDAD BLEADVERTCONFIG
			\ BLEADVERTSTART BLEADVERTSTOP BLEAUTHENTICATE BLEPAIR BLEPAIREX
			\ BLEPAIRINGINFO BLEPAIRINGRESPONSE BLEENCRYPTCONNECTION BLETXPOWERSET
			\ BLETXPWRWHILEPAIRING BLETXPOWERGET BLESECMNGRPASSKEY BLEACCEPTPAIRING
			\ BLEDISCONNECT BLEADVRPTGETSPACE BLESVCCOMMIT BLESECMNGROOBKEY
			\ BLESECMNGROOBPREF BLESECMNGROOBAVAILABLE BLESECMNGRLESCOWNOOBDATAGET
			\ BLESECMNGRLESCPEEROOBDATASET BLEVSPOPEN BLEVSPOPENEX BLEVSPINFO
			\ BLEVSPWRITE BLEVSPREAD BLEGATTCOPEN BLEDISCSERVICEFIRST
			\ BLEDISCSERVICENEXT BLEDISCCHARFIRST BLEDISCCHARNEXT BLEDISCDESCFIRST
			\ BLEDISCDESCNEXT BLEGATTCFINDCHAR BLEGATTCFINDDESC BLEGATTCREAD
			\ BLEGATTCREADDATA BLEGATTCWRITE BLEGATTCWRITECMD BLEGATTCNOTIFYREAD
			\ BLECONNECTCONFIG BLECONNECT BLECONNECTCANCEL BLESCANCONFIG BLESCANSTART
			\ BLESCANFLUSH BLESCANABORT BLESCANSTOP BLESCANGETADVREPORT
			\ BLESCANGETPAGERADDR BLESCANGETADVREPORTEX BLEBONDINGSTATS
			\ BLEBONDINGERASEKEY BLEBONDINGERASEALL BLEBONDINGPERSISTKEY
			\ BLEBONDINGISTRUSTED BLEBONDMNGRGETINFO BLEBONDMNGRERASE
			\ BLEBONDINGADDLESC BLEBONDINGLOADCCCDS BLEBONDINGSAVECCCDS
			\ BLEBONDINGGETBYADDRLESC BLEBONDINGGETBYEDIVLESC BLEBONDINGGETLESC
			\ BLEWHITELISTCREATE BLEWHITELISTCLEAR BLEWHITELISTADDADDR
			\ BLEWHITELISTADDINDEX BLEWHITELISTINFO BLEWHITELISTSETFILTER I2COPEN
			\ I2COPENEX I2CWRITEREAD I2CWRITEREG8 I2CWRITEREG16 I2CWRITEREG32
			\ I2CREADREG8 I2CREADREG16 I2CREADREG32 SPIOPEN SPIREADWRITE SPIWRITE
			\ SPIREAD CRC16GENERATE CRC32GENERATE HASHGENERATE AESSETKEYIV AESENCRYPT
			\ AESDECRYPT ECCGENERATEPUBPRVKEYS ECCCALCSHAREDSECRET ECCHMACSHA256
			\ GPIOCONFIGPWM GPIOSETFUNC GPIOREAD GPIOBINDEVENT GPIOUNBINDEVENT
			\ GPIOASSIGNEVENT GPIOUNASSIGNEVENT GPIOSETFUNCEX BLECONNRSSISTART
			\ BLECONNRSSISTOP FLASHOPEN FLASHREAD FLASHWRITE FLASHERASE
			\ NFCHARDWARESTATE NFCOPEN NFCFIELDSENSE NFCNDEFMSGNEW NFCNDEFMSGDELETE
			\ NFCNDEFMSGCOMMIT NFCNDEFMSGGETINFO NFCNDEFMSGRESET NFCNDEFRECADDLEOOB
			\ NFCNDEFRECADDGENERIC BLEMAXPACKETLENGTHGET BLEGATTCATTRIBUTEMTUREQUEST
			\ BLEGATTCWRITEPREPARE BLEGATTCWRITEEXEC BLEPINGAUTHTIMEOUT
			\ BLECHARVALUEWRITEEX BLECHANNELMAP BLEGETCHANNELMAP SPISLAVEOPEN
			\ SPISLAVECLOSE SPISLAVETXBUFFERWRITE SPISLAVERXBUFFERREAD SPISLAVECONFIG
			\ WDTSTART WDTRESET WDTISRUNNING BLEPHYSET BLEADVSETCREATE BLEADVSETNEWDATA
			\ BLEADVSETSTART BLEADVSETSTOP BLESCANSTARTEX BLEEXTRPTMETADATA
			\ BLECONNECTEXTENDED BLEEXTADVRPTAPPENDAD BLEEXTADVRPTGETSPACE
			\ BLEEXTADVRPTADDUUID16 BLEEXTADVRPTADDUUID128 BLEPAIRINGSTATICPASSKEY

" smartBASIC subroutines
syn keyword smartbasicSubroutine RESETLASTERROR STRDEESCAPE STRSHIFTLEFT CIRCBUFDESTROY STRMOVE STREXCHANGE TIMERSTART TIMERCANCEL UARTCLOSE UARTSETRTS UARTBREAK UARTFLUSH FCLOSE BLECONFIGDCDC BLECONFIGHFCLOCK BLEVSPCLOSE BLEVSPFLUSH BLEVSPUARTBRIDGE BLEGATTCCLOSE SPICLOSE GPIOWRITE RESET ASSERTBL652 RANDSEED BLEWHITELISTDESTROY I2CCLOSE FLASHCLOSE NFCCLOSE

" smartBASIC Event and Message IDs
syn keyword smartbasicEvent EVTMR0 EVTMR1 EVTMR2 EVTMR3 EVTMR4 EVTMR5 EVTMR6 EVTMR7 EVVSPRX EVUARTRX EVUARTCTS EVGPIOCHAN0 EVGPIOCHAN1 EVGPIOCHAN2 EVGPIOCHAN3 EVGPIOCHAN4 EVGPIOCHAN5 EVGPIOCHAN6 EVGPIOCHAN7 EVNOTIFYBUF EVUARTBREAK EVVSPRXOVRN EVATTRNOTIFY EVVSPTXEMPTY EVDETECTCHAN0 EVUARTTXEMPTY EVBLE_ADV_REPORT EVBLE_FAST_PAGED EVBLE_ADV_TIMEOUT EVBLE_EXTADVNOMEM EVBLE_CONN_TIMEOUT EVBLE_SCAN_ABORTED EVBLE_SCAN_TIMEOUT EVBLE_EXTADVDROPPED EVNFC EVBLEMSG EVDISCON EVMSGAPP EVAUTHVAL EVCHARHVC EVCHARVAL EVATTRREAD EVAUTHCCCD EVAUTHDESC EVAUTHSCCD EVCHARCCCD EVCHARDESC EVCHARSCCD EVCONNRSSI EVDISCCHAR EVDISCDESC EVFINDCHAR EVFINDDESC EVATTRWRITE EVAUTHVALEX EVCHARVALUE EVGATTCTOUT EVBLEAUTHINFO EVBLE_AUTHKEY EVBLE_PASSKEY EVDISCPRIMSVC EVATTRIBUTEMTU EVATTRNOTIFYEX EVCONNPARAMREQ EVLESCKEYPRESS EVPACKETLENGTH EVSPISLAVETXRX EVBLESECREQUEST EVBLE_EXTADV_END EVBLE_EXTADV_RPT EVBLE_EXTSCN_RPT EVBLE_PHY_REQUEST EVBLE_PHY_UPDATED EVBLEOVERWRITEBOND EVPACKETLENGTHLIMITED EVSPISLAVERXBUFFERFULL EVBLE_PING_AUTH_TIMEOUT EVSPISLAVETXBUFFEREMPTY EVSPISLAVEBUFFERCONFIGURED EVBLE_EXTADV_RPT_INCOMPLETE

" キーワードの設定
syn keyword myKeywords A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z ? ! ' , . < > / + - _ * & ^ % $ £ " ` \ |

" デリミタの設定
syn match myDelimiters "00\" 01 02\" 03( 04 05) 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"


" Comments
syn match smartbasicComment "//.*" contains=@Spell
syn match smartbasicComment "'[^']*$" contains=@Spell

" Strings
syn match smartbasicString "\"[^\"]*\""

" Define highlighting groups
hi def link smartbasicPreProc PreProc
hi def link smartbasicKeyword1 Keyword
hi def link smartbasicFunction Function
hi def link smartbasicSubroutine Function
hi def link smartbasicEvent Identifier
hi def link smartbasicComment Comment
hi def link smartbasicString String
hi link myKeywords Keyword
hi link myDelimiters Delimiter

let b:current_syntax = "smartbasic"

